#!/usr/bin/perl -p

# special characters
s@<@&lt;@g;  s@]]>@]]&gt;@g; 

s@\b([a-zA-Z][a-zA-Z0-9\.\:-]*\b:?)@<token>$1</token>@g;
s@\"([^\"]*)\"@\"<string>$1</string>\"@g;
# s@([:\*])@<token>$1</token>@g;
s@^(#.*?)\r?$@<comment>$1</comment>@g;

s@&@&amp;@g; 
